project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - timevalue.qmd
    - returns.qmd
  
website:
  title: ""

  navbar:
    background: "#00205B"
    search: true
    left:

      - text: "Home"
        file: index.qmd

      - text: "Time and Money"
        file: timevalue.qmd

      - text: "Returns"
        file: returns.qmd
     
format: 
  html:
    theme: cyborg
    scss: styles.css
    



