project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - timevalue.qmd
    - returns.qmd
    - asset_classes.qmd
    - portfolios.qmd
    - portfolios_capm.qmd
    - corporate.qmd
  
website:
  title: ""

  navbar:
    background: "#00205B"
    search: true
    left:

      - text: "Home"
        file: index.qmd

      - text: "Time and Money"
        file: timevalue.qmd

      - text: "Returns"
        file: returns.qmd
        
      - text: "Asset Classes"
        file: asset_classes.qmd
        
      - text: "Portfolios"
        file: portfolios.qmd
        
      - text: "Portfolios and the CAPM"
        file: portfolios_capm.qmd
        
      - text: "Corporate Investment"
        file: corporate.qmd
     
format: 
  html:
    theme: cyborg
    scss: styles.css
    



