project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - time_and_money.qmd
    - returns.qmd
    - portfolios.qmd
    - corporate.qmd
  
website:
  title: ""
  search: false

  navbar:
    background: "#00205B"
    search: false
    left:
       
      - text: "Home"
        file: index.qmd

      - text: "Time and Money"
        file: time_and_money.qmd

      - text: "Assets and Returns"
        file: returns.qmd
                
      - text: "Portfolios"
        file: portfolios.qmd
              
      - text: "Corporate Investment"
        file: corporate.qmd
     
format: 
  html:
    theme: cyborg
    scss: styles.css
    



